version: "3"
services:

  data_collection:
    build: data_collection
    depends_on:
      - postgres
      - splash
    env_file:
      - .env
    volumes:
      - ./data:/mnt/data
      - ./data_collection:/mnt/code
      - ./database:/mnt/lib/database

  postgres:
    env_file:
      - .env
    image: postgres:alpine
    ports:
      - 5432:5432

  processing:
    build: processing
    depends_on:
      - postgres
    volumes:
      - ./database:/mnt/lib/database
      - ./processing:/mnt/code

  splash:
    image: scrapinghub/splash:3.2
    ports:
      - 5023:5023
      - 8050:8050
